# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(serviceconnection)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azmonitoring'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'Templates/actiongrouptemplate.json'
    csmParametersFile: 'ParameterFiles/ActionGrpParams.json'
    deploymentMode: 'Incremental'
    deploymentName: 'actgrpdeploy'
    deploymentOutputs: actiongrp_arm


- task: AzureResourceManagerTemplateDeployment@3 
  inputs:
   deploymentScope: 'Resource Group'
   azureResourceManagerConnection: $(serviceconnection)
   subscriptionId: $(subscriptionId)
   action: 'Create Or Update Resource Group'
   resourceGroupName: 'azmonitoring'
   location: 'UK South'
   templateLocation: 'Linked artifact'
   csmFile: 'Templates/ResourceHealthTemplate.json'
   deploymentMode: 'Incremental'
   deploymentName: 'RHMonDeploy'
   overrideParameters: -actionGroupResourceId $(actiongrp_arm.actionGroupId.value) -activityLogAlertName 'Resource Health Critical Alerts'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(serviceconnection)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azmonitoring'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'Templates/MultiresourceKVMetric.json'
    overrideParameters: '-actiongroups_id $(actiongrp_arm.actionGroupId.value)'
    deploymentName: "KVmetric"
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'alexInternal'
    subscriptionId: 'db99463c-2a00-433c-a39b-f63083b719a4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azmonitoring'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'Templates/MultiresourceKVMetric.json'
    csmParametersFile: 'ParameterFiles\KVSaturationMetric.json'
    overrideParameters: '-actiongroups_id $(actiongrp_arm.actionGroupId.value)'
    deploymentMode: 'Incremental'
