# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'alexInternal'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create --name $(RGname) --location uksouth --tags "Parent Business"="Shared IT core services" Portfolio="Digital and Technology" Product="CIP Platform" "Service Line"="Cloud and Infrastructure Platforms" "Service Offering"="Infrastructure Business Engagement"'
  
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(serviceconnection)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(RGname)
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'Templates/actiongrouptemplate.json'
    csmParametersFile: 'ParameterFiles/ActionGrpParams.json'
    deploymentMode: 'Incremental'
    deploymentName: 'actgrpdeploy'
    deploymentOutputs: actiongrp_arm


- task: AzureResourceManagerTemplateDeployment@3 
  inputs:
   deploymentScope: 'Resource Group'
   azureResourceManagerConnection: $(serviceconnection)
   subscriptionId: $(subscriptionId)
   action: 'Create Or Update Resource Group'
   resourceGroupName: $(RGname)
   location: 'UK South'
   templateLocation: 'Linked artifact'
   csmFile: 'Templates/ResourceHealthTemplate.json'
   deploymentMode: 'Incremental'
   deploymentName: 'RHMonDeploy'
   overrideParameters: -actionGroupResourceId $(actiongrp_arm.actionGroupId.value) -activityLogAlertName 'Resource Health Critical Alerts RTscope'

- task: AzureResourceManagerTemplateDeployment@3
  condition: eq(variables.keyvault, true)
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(serviceconnection)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(RGName)
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'Templates/MultiresourceKVMetric.json'
    overrideParameters: '-actiongroups_id $(actiongrp_arm.actionGroupId.value)'
    deploymentName: "KVmetric"
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  condition: eq(variables.keyvault, true)
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(serviceconnection)
    subscriptionId: 'db99463c-2a00-433c-a39b-f63083b719a4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(RGName)
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'Templates/MultiresourceKVMetric.json'
    csmParametersFile: 'ParameterFiles/KVSaturationMetric.json'
    overrideParameters: '-actiongroups_id $(actiongrp_arm.actionGroupId.value)'
    deploymentMode: 'Incremental'

- task: AzurePowerShell@5
  condition: and(eq(variables.routetable, true),contains(variables.targetRTrg,'az'))
  inputs:
    azureSubscription: $(serviceconnection)
    ScriptType: 'FilePath'
    ScriptPath: 'Scripts/SetActivityLogAlert.ps1'
    ScriptArguments: 
      -subscriptionId $(subscriptionId) `
      -resourcegroup $(RGname) `
      -actiongroups_id $(actiongrp_arm.actionGroupId.value) `
      -operationName Microsoft.Network/routeTables/routes/write `
      -targetresourcegroup $(targetRTrg) `
      -Alertname Bronze-AAroutetableupdate
    azurePowerShellVersion: 'LatestVersion'
  continueOnError: true

- task: AzurePowerShell@5
  condition: and(eq(variables.routetable, true),eq(variables.targetRTrg,''))
  inputs:
    azureSubscription: $(serviceconnection)
    ScriptType: 'FilePath'
    ScriptPath: 'Scripts/SetActivityLogAlert.ps1'
    ScriptArguments: 
      -subscriptionId $(subscriptionId) `
      -resourcegroup $(RGname) `
      -actiongroups_id $(actiongrp_arm.actionGroupId.value) `
      -operationName Microsoft.Network/routeTables/routes/write `
      -Alertname Bronze-AAroutetableupdate
    azurePowerShellVersion: 'LatestVersion'
  continueOnError: true


- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(serviceconnection)
    ScriptType: 'FilePath'
    ScriptPath: 'Scripts/SetMetricAlert.ps1'
    ScriptArguments: 
      -subscriptionId $(subscriptionId) `
      -resourcegroup $(RGname) `
      -ResourceType microsoft.network/loadbalancers `
      -actiongroups_id $(actiongrp_arm.actionGroupId.value) `
      -metricname VipAvailability `
      -Threshold 90 `
      -Operator LessThan `
      -Alertname HealthProbeLoadBalancer
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(serviceconnection)
    ScriptType: 'FilePath'
    ScriptPath: 'Scripts/SetMetricAlert.ps1'
    ScriptArguments: 
      -subscriptionId $(subscriptionId) `
      -resourcegroup $(RGname) `
      -ResourceType microsoft.network/loadbalancers `
      -actiongroups_id $(actiongrp_arm.actionGroupId.value) `
      -metricname dipAvailability `
      -Threshold 90 `
      -Operator LessThan `
      -Dynamic $true `
      -Alertname DataAvailLoadBalancerdYNAMIC `
      -Description "The Data path Availabiilty of the Load Balancer is below currrent Threshold" 
    azurePowerShellVersion: 'LatestVersion'

    
- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(serviceconnection)
    ScriptType: 'FilePath'
    ScriptPath: 'Scripts/SetMetricAlert.ps1'
    ScriptArguments: 
      -subscriptionId $(subscriptionId) `
      -resourcegroup $(RGname) `
      -ResourceType microsoft.network/loadbalancers `
      -actiongroups_id $(actiongrp_arm.actionGroupId.value) `
      -metricname dipAvailability `
      -Threshold 90 `
      -Operator LessThan `
      -Alertname DataAvailLoadBalancer `
      -Description "The Data path Availabiilty of the Load Balancer is below currrent Threshold" 
    azurePowerShellVersion: 'LatestVersion'



- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(serviceconnection)
    ScriptType: 'FilePath'
    ScriptPath: 'Scripts/MetricwithDimensiontargetted.ps1'
    ScriptArguments: 
      -subscriptionId $(subscriptionId) `
      -resourcegroup $(RGname) `
      -ResourceType microsoft.automation/automationaccounts `
      -resourcename $(automationaccount) ` 
      -actiongroups_id $(actiongrp_arm.actionGroupId.value) `
      -metricname TotalJob `
      -Threshold 0 `
      -Operator GreaterThan `
      -Dim1Name Runbook `
      -Dim1Value $(runbookname) `
      -Dim2Name Status `
      -Dim2Value Failed `
      -Alertname RunbookFail
    azurePowerShellVersion: 'LatestVersion'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(serviceconnection)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(RGName)
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'Templates/laresultquery.json'
    csmParametersFile: 'ParameterFiles/ExampleLAMetricQueryPara.json'
    overrideParameters: '-actionGroupId $(actiongrp_arm.actionGroupId.value)'
    deploymentName: "LAQueryDep"
    deploymentMode: 'Incremental'
 
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(serviceconnection)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(RGName)
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'Templates/DataCollectionRuleWindows.json'
    deploymentName: "LAQueryDep"
    deploymentMode: 'Incremental'





